#pragma once
#include <execution/sched/context/context_type.h>

synapse_execution_export
synapse_execution_sched_context
synapse_execution_sched_context_initialize
	(synapse_memory_pooling_dynamic_traits*, synapse_execution_sched_queue_traits*);

synapse_execution_export
void
synapse_execution_sched_context_cleanup
	(synapse_execution_sched_context);