#pragma once
#include <execution/sched/system_sched/syssched_type.h>

synapse_execution_export
synapse_execution_sched_system
synapse_execution_sched_system_initialize
	(synapse_memory_pooling_dynamic_traits*);

synapse_execution_export
void
synapse_execution_sched_system_cleanup
	(synapse_execution_sched_system);